// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2619.SteamBot2017.subsystems;

import org.usfirst.frc2619.SteamBot2017.RobotMap;
import org.usfirst.frc2619.SteamBot2017.TheChargeDashboard;
import org.usfirst.frc2619.SteamBot2017.commands.*;
import com.ctre.CANTalon;
import com.ctre.CANTalon.TalonControlMode;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class BallPickup extends Subsystem {
	private final static double PICKUP_P_CONSTANT = 0.3;
	private final static double PICKUP_I_CONSTANT = 0.001;
	private final static double PICKUP_D_CONSTANT = 0.0;
	private final static double PICKUP_F_CONSTANT = 0.12;

	double SpeedP = PICKUP_P_CONSTANT;
	double SpeedI = PICKUP_I_CONSTANT;
	double SpeedD = PICKUP_D_CONSTANT;
	double SpeedF = PICKUP_F_CONSTANT;

	private final static int MAX_TICKS_PER_SECOND = 8691;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon pickupMotor = RobotMap.ballPickupPickupMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	// Put methods for controlling this subsystem
	// here. Call these from Commands.

	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}

	public void writeDefaultDashboardValues() {
		TheChargeDashboard.putNumber("PickupSpeedP", PICKUP_P_CONSTANT);
		TheChargeDashboard.putNumber("PickupSpeedI", PICKUP_I_CONSTANT);
		TheChargeDashboard.putNumber("PickupSpeedD", PICKUP_D_CONSTANT);
		TheChargeDashboard.putNumber("PickupSpeedF", PICKUP_F_CONSTANT);
	}

	public void readDashboardControlValues() {
		SpeedP = SmartDashboard.getNumber("PickupSpeedP", PICKUP_P_CONSTANT);
		SpeedI = SmartDashboard.getNumber("PickupSpeedI", PICKUP_I_CONSTANT);
		SpeedD = SmartDashboard.getNumber("PickupSpeedD", PICKUP_D_CONSTANT);
		SpeedF = SmartDashboard.getNumber("PickupSpeedF", PICKUP_F_CONSTANT);

		// set CANTalon PIDs
		pickupMotor.setPID(SpeedP, SpeedI, SpeedD, SpeedF, 0, 0, 0);
	}

	public void initSpeedPercentageMode() {
		pickupMotor.changeControlMode(TalonControlMode.Speed);

		pickupMotor.setProfile(0);

		pickupMotor.configMaxOutputVoltage(12);
	}

	public void set(double percentSpeed) {
		// Sets what speed the motors will run at.
		pickupMotor.setSetpoint(MAX_TICKS_PER_SECOND * percentSpeed);
	}

	public void writeDebugValues() {
		TheChargeDashboard.putNumber("PickupSetpoint", pickupMotor.getSetpoint());
		TheChargeDashboard.putNumber("PickupMotorControlSpeed", pickupMotor.getSpeed());
		TheChargeDashboard.putNumber("PickupMscOutput", pickupMotor.getOutputVoltage());
		TheChargeDashboard.putNumber("PickupMotorVelocity", pickupMotor.getEncVelocity());
	}
}
