// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2619.SteamBot2017;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DigitalOutput;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.Solenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import com.kauailabs.navx.frc.AHRS;
import edu.wpi.first.wpilibj.SPI.Port;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTrainLeftFrontMotor;
    public static WPI_TalonSRX driveTrainRightFrontMotor;
    public static WPI_TalonSRX driveTrainRightRearMotor;
    public static WPI_TalonSRX driveTrainLeftRearMotor;
    public static AnalogGyro driveTrainDoNotUse;
    public static Solenoid shiftersSolenoid;
    public static WPI_TalonSRX shooterMotorsMotor;
    public static Solenoid gearPlungerPlunger;
    public static Solenoid gearDoorsDoors;
    public static Relay ledBoardLedSpike;
    public static DigitalOutput ledBoardLedOutput0;
    public static DigitalOutput ledBoardLedOutput1;
    public static DigitalOutput ledBoardLedOutput2;
    public static DigitalOutput ledBoardLedOutput3;
    public static WPI_TalonSRX ropeClimberRopeMotor1;
    public static WPI_TalonSRX ropeClimberRopeMotor2;
    public static DigitalInput ropeClimberRopeDI;
    public static Relay cameraLightsCameraSpike;
    public static WPI_TalonSRX ballPickupPickupMotor;
    public static WPI_TalonSRX indexerIndexerMotor;
    public static DigitalInput indexerIndexerDI;
    public static AnalogInput ultrasonicUltrasonicSensor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static final int TIMEOUT_MS = 100;

	public static AHRS driveTrainAHRS;

	public static void init() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftFrontMotor = new WPI_TalonSRX(11);
        LiveWindow.addActuator("DriveTrain", "LeftFrontMotor", driveTrainLeftFrontMotor);
        
        driveTrainRightFrontMotor = new WPI_TalonSRX(2);
        LiveWindow.addActuator("DriveTrain", "RightFrontMotor", driveTrainRightFrontMotor);
        
        driveTrainRightRearMotor = new WPI_TalonSRX(3);
        LiveWindow.addActuator("DriveTrain", "RightRearMotor", driveTrainRightRearMotor);
        
        driveTrainLeftRearMotor = new WPI_TalonSRX(10);
        LiveWindow.addActuator("DriveTrain", "LeftRearMotor", driveTrainLeftRearMotor);
        
        driveTrainDoNotUse = new AnalogGyro(0);
        LiveWindow.addSensor("DriveTrain", "DoNotUse", driveTrainDoNotUse);
        driveTrainDoNotUse.setSensitivity(0.007);
        shiftersSolenoid = new Solenoid(0, 0);
        LiveWindow.addActuator("Shifters", "Solenoid", shiftersSolenoid);
        
        shooterMotorsMotor = new WPI_TalonSRX(7);
        LiveWindow.addActuator("ShooterMotors", "Motor", shooterMotorsMotor);
        
        gearPlungerPlunger = new Solenoid(0, 2);
        LiveWindow.addActuator("GearPlunger", "Plunger", gearPlungerPlunger);
        
        gearDoorsDoors = new Solenoid(0, 1);
        LiveWindow.addActuator("GearDoors", "Doors", gearDoorsDoors);
        
        ledBoardLedSpike = new Relay(1);
        LiveWindow.addActuator("LedBoard", "LedSpike", ledBoardLedSpike);
        
        ledBoardLedOutput0 = new DigitalOutput(0);
        LiveWindow.addActuator("LedBoard", "LedOutput0", ledBoardLedOutput0);
        
        ledBoardLedOutput1 = new DigitalOutput(1);
        LiveWindow.addActuator("LedBoard", "LedOutput1", ledBoardLedOutput1);
        
        ledBoardLedOutput2 = new DigitalOutput(2);
        LiveWindow.addActuator("LedBoard", "LedOutput2", ledBoardLedOutput2);
        
        ledBoardLedOutput3 = new DigitalOutput(3);
        LiveWindow.addActuator("LedBoard", "LedOutput3", ledBoardLedOutput3);
        
        ropeClimberRopeMotor1 = new WPI_TalonSRX(4);
        LiveWindow.addActuator("RopeClimber", "RopeMotor1", ropeClimberRopeMotor1);
        
        ropeClimberRopeMotor2 = new WPI_TalonSRX(5);
        LiveWindow.addActuator("RopeClimber", "RopeMotor2", ropeClimberRopeMotor2);
        
        ropeClimberRopeDI = new DigitalInput(4);
        LiveWindow.addSensor("RopeClimber", "RopeDI", ropeClimberRopeDI);
        
        cameraLightsCameraSpike = new Relay(0);
        LiveWindow.addActuator("CameraLights", "CameraSpike", cameraLightsCameraSpike);
        
        ballPickupPickupMotor = new WPI_TalonSRX(6);
        LiveWindow.addActuator("BallPickup", "PickupMotor", ballPickupPickupMotor);
        
        indexerIndexerMotor = new WPI_TalonSRX(8);
        LiveWindow.addActuator("Indexer", "IndexerMotor", indexerIndexerMotor);
        
        indexerIndexerDI = new DigitalInput(5);
        LiveWindow.addSensor("Indexer", "IndexerDI", indexerIndexerDI);
        
        ultrasonicUltrasonicSensor = new AnalogInput(1);
        LiveWindow.addSensor("Ultrasonic", "UltrasonicSensor", ultrasonicUltrasonicSensor);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

		driveTrainAHRS = new AHRS(Port.kMXP);
		driveTrainRightFrontMotor.setInverted(true);
		driveTrainRightRearMotor.setInverted(true);

		// Change Right motor to follow mode
		driveTrainRightRearMotor.set(ControlMode.Follower, driveTrainRightFrontMotor.getDeviceID());
		// Set the device to follow the front motor with encoder
		//driveTrainRightRearMotor.set(driveTrainRightFrontMotor.getDeviceID());

		// Change Left motor to follow mode
		driveTrainLeftRearMotor.set(ControlMode.Follower, driveTrainLeftFrontMotor.getDeviceID());
		// Set the device to follow the front motor with encoder
		//driveTrainLeftRearMotor.set(driveTrainLeftFrontMotor.getDeviceID());
	}
}
