// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2619.SteamBot2017.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc2619.SteamBot2017.Robot;
import org.usfirst.frc2619.SteamBot2017.RobotMap;

/**
 *
 */
public class RunLed extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public RunLed() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.ledBoard);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.ledBoard.initLEDValue();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	int choice = (int)SmartDashboard.getNumber("LEDOutput");
    	
    	//bitmapping
    	if((choice & 0b0001) == 0b0001)
    		RobotMap.ledBoardLedOutput0.set(true);
    	else
    		RobotMap.ledBoardLedOutput0.set(false);
    	if((choice & 0b0010) == 0b0010)
    		RobotMap.ledBoardLedOutput1.set(true);
    	else
    		RobotMap.ledBoardLedOutput1.set(false);
    	if((choice & 0b0100) == 0b0100)
    		RobotMap.ledBoardLedOutput2.set(true);
    	else
    		RobotMap.ledBoardLedOutput2.set(false);
    	if((choice & 0b1000) == 0b1000)
    		RobotMap.ledBoardLedOutput3.set(true);
    	else
    		RobotMap.ledBoardLedOutput3.set(false);
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
