// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2619.SteamBot2017.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2619.SteamBot2017.Robot;

import com.ctre.CANTalon;
import com.ctre.CANTalon.TalonControlMode;

/**
 *
 */
public class TurnNDegreesAbsolute extends Command {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	private double m_nDegrees;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	private CANTalon.TalonControlMode previousControlMode;

	private double degreeChange;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	public TurnNDegreesAbsolute(double nDegrees) {

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		m_nDegrees = nDegrees;

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}

	// Called just before this Command runs the first time
	protected void initialize() {
		previousControlMode = Robot.driveTrain.getControlMode();
		double yawInitial = Robot.driveTrain.getYaw();
		// Calculates the shortest path to m_nDegrees
		// Positive degreeChange means move to the right, negative degreeChange
		// means move to the left
		if (((yawInitial <= 0) && (m_nDegrees <= 0)) || ((yawInitial >= 0) && (m_nDegrees >= 0)))
			degreeChange = m_nDegrees - yawInitial;
		else if ((yawInitial > 0) && (m_nDegrees < 0)) {
			if (yawInitial - m_nDegrees <= 180)
				degreeChange = m_nDegrees - yawInitial;
			else
				degreeChange = 360 + (m_nDegrees - yawInitial);

		} else if ((yawInitial < 0) && (m_nDegrees > 0)) {
			if (m_nDegrees - yawInitial <= 180)
				degreeChange = m_nDegrees - yawInitial;
			else
				degreeChange = -360 + (m_nDegrees - yawInitial);
		}
		this.setTimeout(10);
		Robot.driveTrain.setControlMode(TalonControlMode.PercentVbus);
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute() {
		Robot.driveTrain.absTurn(degreeChange, .5);
	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished() {
		// Runs robot until yaw is within 4 degrees
		if (Math.abs(m_nDegrees - Robot.driveTrain.getYaw()) < 4)
			return true;
		else if (this.isTimedOut())
			return true;
		else
			return false;
	}

	// Called once after isFinished returns true
	protected void end() {
		Robot.driveTrain.stop();
		Robot.driveTrain.setControlMode(previousControlMode);
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted() {
		end();
	}
}
